branch-defaults:
  10_backend_for_frontend:
    environment: feodorius-bff-api-prod
    group_suffix: null
global:
  application_name: feodorius-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
